<a href="https://colab.research.google.com/github/shyamsolanke/DRS_System_Cricket/blob/main/Copy_of_Homework2b_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework 1 Part 2: SQL

To start with, if you felt the class was unclear, check out the following tutorial: https://mode.com/sql-tutorial/introduction-to-sql/

Now! We'll be using sqlite to access a database. Start by downloading the sql lite file and putting it in the same directory as this notebook: https://www.kaggle.com/datasets/kaggle/sf-salaries (hit the 'download' button in the upper right). Check out the description of the data so you know the table / column names.

The following code will use sqlite to create a database connection.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("/content/drive/MyDrive/Colab Notebooks/Intro to DS UMD/database.sqlite")
crsr = conn.cursor()

Before we proceed, please note that every task **must be completed using a single SQL query**, unless mentioned otherwise or given as prompt.     
(e.g. using print statements are fine, but you should not be using pandas library to work with the dataset.) The query should be stored in the query variable, like so:

query = 'your query here'

# Exploration

Problem 1:

Try to create a query that gives you a data frame of the EmployeeName, JobTitle, and BasePay from the salaries table.

In [3]:

query = 'SELECT EmployeeName, JobTitle, BasePay FROM Salaries'

df = pd.read_sql(query, conn)
df.head()

,EmployeeName,JobTitle,BasePay
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6

Problem 2.

Modify your query from Problem 1 to limit it to the year 2012.

In [4]:
query = 'SELECT EmployeeName, JobTitle, BasePay FROM Salaries where year=2012'

df = pd.read_sql(query, conn)
df.head()

         EmployeeName                      JobTitle    BasePay
0      Gary Altenberg  Lieutenant, Fire Suppression  128808.87
1        Gregory Suhr               Chief of Police  302578.00
2          Khoa Trinh   Electronic Maintenance Tech  111921.00
3  Joanne Hayes-White        Chief, Fire Department  296943.01
4   Frederick Binkley     EMT/Paramedic/Firefighter  126863.19

Problem 3:

Further limit the table to the year 2012, employees making under 150,000, and sort in descending order by salary.

In [6]:
query = 'SELECT EmployeeName, JobTitle, Basepay, YEAR FROM salaries WHERE YEAR = 2012 AND BASEPAY < 150000 ORDER By Basepay desc'

df = pd.read_sql(query, conn)
df.head()

           EmployeeName                     JobTitle    BasePay  Year
0      Julie Kirschbaum            Project Manager 3  149881.06  2012
1          Eric Jamison  Senior Physician Specialist  149746.72  2012
2  Daisy Mae Quitoriano                Nurse Manager  149657.87  2012
3        Ruth Armstrong           Nurse Practitioner  149169.48  2012
4     Stuart Washington  Senior Physician Specialist  148811.73  2012

# Aggregation

Problem 4:

Get the average base pay from the table.

In [ ]:
df.columns

Index(['EmployeeName', 'JobTitle', 'TotalPay', 'Year'], dtype='object')

In [7]:
query = 'SELECT AVG(BASEPAY) FROM SALARIES'

df = pd.read_sql(query, conn)
df.head()

   AVG(BASEPAY)
0  66053.729288

Problem 5:

Produce and print the head of a dataframe that shows the average pay for each year (only use a single, simple query). Your result should have a column for the year and a column for the average base pay.

In [8]:
query = 'SELECT AVG(BasePAY) as AVGbasePAY, YEAR as year FROM SALARIES GROUP BY YEAR '

df = pd.read_sql(query, conn)
df.head()

     AVGbasePAY  year
0  63595.956517  2011
1  65436.406857  2012
2  68509.832156  2013
3  66557.437750  2014

Problem 6:

Create a dataframe with averages of base pay, benefits, and overtime for each job title, as well as a column with the average of these three values.

In [9]:
query = 'SELECT AVG(BASEPAY), AVG(BENEFITS), AVG(OvertimePay), jobtitle , (AVG(BASEPAY) + AVG(BENEFITS) + AVG(OvertimePay))/3 as AVGOFAVGBASE_BENEFIT_OVERTIME FROM SALARIES GROUP BY JOBTITLE'
df = pd.read_sql(query, conn)
df.head(25)

,AVG(BASEPAY),AVG(BENEFITS),AVG(OvertimePay),JobTitle,AVGOFAVGBASE_BENEFIT_OVERTIME
0,43300.806506,0.00,373.200843,ACCOUNT CLERK,14558.002450
1,46643.172000,0.00,0.000000,ACCOUNTANT,15547.724000
2,28732.663958,0.00,24.430625,ACCOUNTANT INTERN,9585.698194
3,62290.780000,17975.59,0.000000,"ACPO,JuvP, Juv Prob (SFERS)",26755.456667
4,66374.400000,0.00,0.000000,ACUPUNCTURIST,22124.800000
5,63435.628602,0.00,0.000000,ADMINISTRATIVE ANALYST,21145.209534
6,59373.710000,0.00,0.000000,ADMINISTRATIVE ANALYST II,19791.236667
7,92698.515000,0.00,0.000000,ADMINISTRATIVE ANALYST III,30899.505000
8,120913.161000,0.00,0.000000,ADMINISTRATIVE ENGINEER,40304.387000
9,75555.033333,0.00,0.000000,ADMINISTRATIVE SERVICES MANAGER,25185.011111
10,245124.440000,0.00,0.000000,"ADMINISTRATOR, SFGH MEDICAL CENTER",81708.146667
11,68177.316667,0.00,0.000000,AFFIRMATIVE ACTION SPECIALIST,22725.772222
12,53274.100000,0.00,0.000000,AGRICULTURAL INSPECTOR,17758.033333
13,1927.500000,0.00,0.000000,"AIRPORT ASSISTANT DEPUTY DIRECTOR, BUSINESS AD...",642.500000
14,15420.000000,0.00,0.000000,"AIRPORT ASSISTANT DEPUTY DIRECTOR, OPERATIONS",5140.000000
15,67643.142593,0.00,10126.440000,AIRPORT COMMUNICATIONS OPERATOR,25923.194198
16,86585.825000,0.00,255.135000,AIRPORT COMMUNICATIONS SUPERVISOR,28946.986667
17,108145.590769,0.00,0.000000,AIRPORT ECONOMIC PLANNER,36048.530256
18,95488.671765,0.00,7453.082941,AIRPORT ELECTRICIAN,34313.918235
19,104203.725000,0.00,2851.135000,AIRPORT ELECTRICIAN SUPERVISOR,35684.953333
20,75865.935000,0.00,0.000000,AIRPORT EMERGENCY PLANNING COORDINATOR,25288.645000
21,118978.520000,0.00,0.000000,AIRPORT MECHANICAL MAINTENANCE SUPERVISOR,39659.506667
22,49108.725000,0.00,0.000000,AIRPORT NOISE ABATEMENT SPECIALIST,16369.575000
23,84760.671667,0.00,5950.677500,AIRPORT OPERATIONS SUPERVISOR,30237.116389
24,51178.742834,0.00,5478.936096,AIRPORT POLICE SERVICES AIDE,18885.892977

# Table Creation

Problem 7:

Now we'll create our own table in our database. Separate the Salaries table by Year, and add it back to the database. (You may use basic python to complete the task, however, should still use SQL to query the data.)

In [10]:
listA = ['2011','2012','2013','2014']
print(listA)
for y in listA:
    print(y)
    query = f"CREATE TABLE Table{y} AS SELECT * FROM SALARIES WHERE YEAR='{y}'" # removed SET NOCOUNT ON; from the query
    try:
      df = pd.read_sql(query, conn)
    except Exception as e:
      print(e)
      pass
    df.to_sql(name='Y'+y, con=conn,index="False", if_exists='replace')

['2011', '2012', '2013', '2014']
2011
Execution failed on sql 'CREATE TABLE Table2011 AS SELECT * FROM SALARIES WHERE YEAR='2011'': table Table2011 already exists
2012
Execution failed on sql 'CREATE TABLE Table2012 AS SELECT * FROM SALARIES WHERE YEAR='2012'': table Table2012 already exists
2013
Execution failed on sql 'CREATE TABLE Table2013 AS SELECT * FROM SALARIES WHERE YEAR='2013'': table Table2013 already exists
2014
Execution failed on sql 'CREATE TABLE Table2014 AS SELECT * FROM SALARIES WHERE YEAR='2014'': table Table2014 already exists

# Table Joining

Problem 8:

We'll move on to a new dataset for the next steps.
Download the dataset from here (https://www.kaggle.com/datasets/luizpaulodeoliveira/imdb-project-sql) and load the sqlite file same as before. Start by just selecting everything in the "movies" table to see what it looks like.

In [11]:

conn = sqlite3.connect("/content/drive/MyDrive/Colab Notebooks/Intro to DS UMD/movies.sqlite")
crsr = conn.cursor()
query = 'SELECT * FROM MOVIES'

df = pd.read_sql(query, conn)
df.head()

,id,original_title,budget,popularity,release_date,revenue,title,vote_average,vote_count,overview,tagline,uid,director_id
0,43597,Avatar,237000000,150,2009-12-10,2787965087,Avatar,7.2,11800,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,19995,4762
1,43598,Pirates of the Caribbean: At World's End,300000000,139,2007-05-19,961000000,Pirates of the Caribbean: At World's End,6.9,4500,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.",285,4763
2,43599,Spectre,245000000,107,2015-10-26,880674609,Spectre,6.3,4466,A cryptic message from Bond’s past sends him o...,A Plan No One Escapes,206647,4764
3,43600,The Dark Knight Rises,250000000,112,2012-07-16,1084939099,The Dark Knight Rises,7.6,9106,Following the death of District Attorney Harve...,The Legend Ends,49026,4765
4,43601,John Carter,260000000,43,2012-03-07,284139100,John Carter,6.1,2124,"John Carter is a war-weary, former military ca...","Lost in our world, found in another.",49529,4766

Problem 9:

Create a dataframe that includes the entire contents of "movies" table as well as the director's name.

In [12]:
query = '''SELECT movies.*, directors.name as director_name FROM MOVIES LEFT JOIN DIRECTORS
ON MOVIES.DiRECTOR_ID=DIRECTORS.ID order by revenue desc'''
df = pd.read_sql(query, conn)
df.head(11)

,id,original_title,budget,popularity,release_date,revenue,title,vote_average,vote_count,overview,tagline,uid,director_id,director_name
0,43597,Avatar,237000000,150,2009-12-10,2787965087,Avatar,7.2,11800,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,19995,4762,James Cameron
1,43622,Titanic,200000000,100,1997-11-18,1845034188,Titanic,7.5,7562,"84 years later, a 101-year-old woman named Ros...",Nothing on Earth could come between them.,597,4762,James Cameron
2,43613,The Avengers,220000000,144,2012-04-25,1519557910,The Avengers,7.4,11776,When an unexpected enemy emerges and threatens...,Some assembly required.,24428,4769,Joss Whedon
3,43625,Jurassic World,150000000,418,2015-06-09,1513528810,Jurassic World,6.5,8662,Twenty-two years after the events of Jurassic ...,The park is open.,135397,4783,Colin Trevorrow
4,43641,Furious 7,190000000,102,2015-04-01,1506249360,Furious 7,7.3,4176,Deckard Shaw seeks revenge against Dominic Tor...,Vengeance Hits Home,168259,4794,James Wan
5,43604,Avengers: Age of Ultron,280000000,134,2015-04-22,1405403694,Avengers: Age of Ultron,7.3,6767,When Tony Stark tries to jumpstart a dormant p...,A New Age Has Come.,99861,4769,Joss Whedon
6,43721,Frozen,150000000,165,2013-11-27,1274219009,Frozen,7.3,5295,Young princess Anna of Arendelle dreams about ...,Only the act of true love will thaw a frozen h...,109445,4844,Chris Buck
7,43628,Iron Man 3,200000000,77,2013-04-18,1215439994,Iron Man 3,6.8,8806,When Tony Stark's world is torn apart by a for...,Unleash the power behind the armor.,68721,4784,Shane Black
8,44143,Minions,74000000,875,2015-06-17,1156730962,Minions,6.4,4571,"Minions Stuart, Kevin and Bob are recruited by...","Before Gru, they had a history of bad bosses",211672,5045,Kyle Balda
9,43623,Captain America: Civil War,250000000,198,2016-04-27,1153304495,Captain America: Civil War,7.1,7241,"Following the events of Age of Ultron, the col...",Divided We Fall,271110,4781,Anthony Russo
10,43649,Transformers: Dark of the Moon,195000000,28,2011-06-28,1123746996,Transformers: Dark of the Moon,6.1,3299,Sam Witwicky takes his first tenuous steps int...,The invasion we always feared. An enemy we nev...,38356,4788,Michael Bay

# Analysis

The next few problems will be more involved! You'll need to combine some concepts you've learned. For each cell, show your work.
\
Remember, the answers should be in **a single query**.

\
Problem 10:

What is the average budget used for the top 10 grossing movies?

In [20]:
query = '''SELECT AVG(revenue) AS avgtop10revenue FROM (SELECT revenue, row_number() OVER (ORDER BY revenue DESC) AS rn FROM movies) movies WHERE rn <= 10;'''
df = pd.read_sql(query, conn)
df.head(5)

   avgtop10revenue
0     1.537743e+09

Problem 11:

Which directors have the highest overall voting average? - show the top 5 directors' name and their average rating

In [15]:
query = '''SELECT movies.vote_average as voting_average, directors.name as director_name FROM MOVIES LEFT JOIN DIRECTORS
ON MOVIES.DiRECTOR_ID=DIRECTORS.ID order by voting_average desc LIMIT 5'''
df = pd.read_sql(query, conn)
df.head(5)

   voting_average   director_name
0            10.0     Gary Sinyor
1            10.0   Tim McCanlies
2             9.5    Rohit Jugraj
3             9.3      Lance Hool
4             8.5  Frank Darabont

Problem 12:

What are the top five directors by how much their average budget is?

In [14]:
query = '''SELECT directors.name as director_name, AVG(budget) as average_budget FROM MOVIES LEFT JOIN DIRECTORS
ON MOVIES.DiRECTOR_ID=DIRECTORS.ID group by director_name order by average_budget desc LIMIT 5'''
df = pd.read_sql(query, conn)
df.head(5)

    director_name  average_budget
0    Byron Howard    2.600000e+08
1     Lee Unkrich    2.000000e+08
2     Dan Scanlon    2.000000e+08
3     David Yates    1.933333e+08
4  Brenda Chapman    1.850000e+08